# Generated by Django 5.1.1 on 2025-02-19 09:56

import Grocery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery', '0005_vendor_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(default='vendor.jpg', upload_to=Grocery.models.user_directory_path),
        ),
    ]
